Controller/ControllerBook.php, Model/Model.php, Model/ModelUser.php, View/base_html.php, View/homepage.php, View/template_part/footer.php, View/template_part/header.php, index.php
route ob start home page and extends model class
=> route ob start home page and extends model class

Controller/ControllerBook.php, Model/ModelBook.php, View/homepage.php, composer.json, entity/Book.php
Create Model book and display book img with title and editor
=> Create Model book and display book img with title and editor

Controller/ControllerBook.php, Model/ModelBook.php, View/homepage.php, entity/BookDTO.php
add BookDTO with author and illustrator fullname and display in homepage
=> add BookDTO with author and illustrator fullname and display in homepage

Controller/ControllerUser.php, View/login.php
stay connected checkbox with setcookie for 30 days login page
=> stay connected checkbox with setcookie for 30 days login page

Controller/ControllerBook.php, Model/ModelBook.php, View/zeroTwo.php, assets/js/type.js, index.php
fetch for display type of book with age
=> fetch for display type of book with age

Controller/ControllerBook.php, Model/ModelBook.php, View/age.php, View/confirm-token.php, View/confirmation.php, View/homepage.php, View/login.php, View/register-child.php, View/register.php, View/template_part/header.php, View/zeroTwo.php, entity/Age.php, index.php
page age dynamic for each age with category option type
=> page age dynamic for each age with category option type

Controller/ControllerBook.php, Model/ModelBook.php, View/onebook.php, index.php
=> page for each book on book/id

Controller/ControllerUser.php, Model/ModelUser.php, View/base_htmlA.php, View/dashboard.php, View/loginAdmin.php, View/template_part/footerA.php, View/template_part/headerA.php, index.php
route login dashboard dashboard page
=> route login dashboard dashboard page

Controller/ControllerUser.php, Model/ModelUser.php, View/dashboard.php, composer.json, composer.lock, index.php
generate card id and andd dependece for .env files
=> generate card id and andd dependece for .env files

Controller/ControllerUser.php, Model/ModelUser.php, View/dashboard.php, entity/Borrow.php
=> Dashboard search by borrow

Controller/ControllerUser.php, Model/ModelUser.php, View/dashboard.php, entity/Reservation.php
avaibility for reservation and delete button
=> avaibility for reservation and delete button 

View/template_part/header.php, config/config.php, index.php
rewrite url for assets or img with constant to header
=> rewrite url for assets or img with constant to header

Controller/ControllerChild.php, Model/ModelChild.php, View/homepage.php, assets/js/homepage.js, index.php
modif reservation homepage.js modelChild ControllerChild
=> modif reservation homepage.js modelChild ControllerChild

Controller/ControllerChild.php, assets/js/homepage.js
add reservation to bdd with reservation button working !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=> add reservation to bdd with reservation button working !!!!!!!!!!!!!!!!!!

Controller/ControllerChild.php, Model/ModelChild.php, View/homepage.php, assets/js/homepage.js, entity/ReservationDTO.php, index.php
reservation box for each child
=> reservation box for each child

Controller/ControllerChild.php, View/homepage.php, assets/js/homepage.js, index.php
=> delete reservation onclick

View/homepage.php, assets/js/homepage.js
redirect card book page and reservation and login if not connected
=> redirect card book page and reservation and login if not connected

View/register.php, assets/css/style.scss
=> inscription

View/dashboard.php
=> correction

Controller/ControllerUser.php, Model/ModelUser.php, View/parameter.php, View/profil.php, View/template_part/header.php, entity/ReservationDTE.php, index.php
=> page profil debut

Controller/ControllerUser.php, Model/ModelUser.php
modifier mot de passe fonctionnel
=> modifier mot de passe fonctionnel

View/dashboard_modify_book.php, assets/css/style.scss, assets/js/dashboard_modify_book.js
suite et fin avec le close button
=> modifyBook2

Controller/ControllerUser.php, Model/ModelUser.php, View/dashboard.php, assets/js/dashboard_user_stat.js, index.php
dashboard select user fonctionnel !!!!!!!!!!!!!!!!!!!
=> dashboard select user fonctionnel !!!!!!!!!!!!!!!!!!!

View/age.php, assets/js/homepage.js, assets/js/onebook.js
Ajout des dé homepage connecté sans animation
=> Ajout des dé homepage connecté sans animation

Controller/ControllerUser.php, Model/ModelUser.php, View/age.php, View/dashboard.php, assets/js/homepage.js, assets/js/type.js, entity/ReservationDT02.php
page age reservation bug non fonctionnel et bug page dashboard
=> page age reservation bug non fonctionnel et bug page dashboard

Controller/ControllerUser.php, View/dashboard.php, assets/js/type.js
=> modif dashboard fonctionnel

View/dashboard_modify_book.php, View/dashboard_stock_book.php, assets/css/style.scss, assets/js/dashboard_modify_book.js, assets/js/dashboard_stock_book.js
J'ai uniformisé les li du searchForm aussi, et le décalage que j'avais quand on cliquait sur modifier dans le stockbook: j'ai remplacé display none par visibility hidden dans le js. J'ai dû faire quelques réglages avec des if dans le js aussi pour pouvoir styliser les li du searchForm, tout est ok
=> overlayModifyLivres

Controller/ControllerBook.php, Controller/ControllerChild.php, Controller/ControllerUser.php, View/age.php, View/homepage.php, assets/js/homepage.js, assets/js/type.js, index.php
page type fonctionnel un seul enfant est selectionnable
=> page type fonctionnel un seul enfant est selectionnable

View/homepage.php, assets/css/style.scss, assets/js/homepage.js
J'ai utilisé une branche déjà pushée pour le faire du coup j'ai changé de branche et enregistré sur celle-ci, je ne suis pas sure que ça va fonctionner (j'ai réussi le responsive de la page d'accueil). Au cas où, j'ai tout copié collé mon code dans un bloc note
=> Responsive accueil

View/homepage.php, assets/css/style.scss, assets/js/homepage.js
j'ai essayé de renvoyer celle où j'ai fait tout mon travail au cas où
=> Accueil marges

assets/css/style.scss
ça termine le responsive non connecté
=> Resp inscription

assets/css/style.scss
correction double hover sur modi user
=> correction double hover sur modi user

View/template_part/footer.php
4 caractères de chemins absolue
=> 4 caractères de chemins absolue

Controller/ControllerUser.php, Model/ModelUser.php, View/age.php, View/dashboard.php, View/onebook.php, assets/js/homepage.js, assets/js/onebook.js, assets/js/type.js
nettoyage et ajout de commentaire
=> nettoyage et ajout de commentaire
